In [81]:
%load_ext autoreload
%autoreload 2

In [4]:
import numpy as np
import pandas as pd

In [84]:
b = genetic_algorithm()

Módulo aberto com sucesso!


In [85]:
init_pop = b.initial_pop(size_pop=10,size_cromossomo=5,minimum=0.01,maximum=0.5)
init_pop

array([[0.31985499, 0.29462009, 0.41494267, 0.37113957, 0.48308037],
       [0.27918049, 0.07089884, 0.1871817 , 0.17959384, 0.03099241],
       [0.1990294 , 0.35228677, 0.46233328, 0.26845208, 0.29697218],
       [0.16603895, 0.3513434 , 0.43885069, 0.21144309, 0.15057995],
       [0.2207317 , 0.38482847, 0.25756485, 0.28818242, 0.42570979],
       [0.48385072, 0.33713667, 0.22345419, 0.30436709, 0.03533569],
       [0.07428928, 0.405592  , 0.0669775 , 0.03780436, 0.17637204],
       [0.04081646, 0.32716646, 0.26211098, 0.10251775, 0.25539491],
       [0.15499473, 0.11185281, 0.35294066, 0.48988025, 0.13085925],
       [0.42505862, 0.0563207 , 0.45634026, 0.03056634, 0.4129953 ]])

In [86]:
pressoes_r = np.array([2, 3, 5])
def rede(rugosidade):
    pressaoes_0 = rugosidade[0] +rugosidade[1]-rugosidade[2]+rugosidade[4]*rugosidade[3] 
    pressaoes_1 = rugosidade[1]-rugosidade[3]-rugosidade[2]+rugosidade[2]+rugosidade[1]*rugosidade[4]
    pressaoes_2 = rugosidade[4]*rugosidade[3]+rugosidade[2]+rugosidade[1]*rugosidade[2]-rugosidade[2]
    return (pressaoes_0,pressaoes_1,pressaoes_2)

In [87]:
resultado = []
for i in init_pop:
    resultado.append(rede(i))

In [88]:
resultado

[(0.37882265516550495, 0.06580570247941386, 0.3015406844612503),
 (0.16846367798512635, -0.10649767520876736, 0.018837011634681017),
 (0.16870569268635616, 0.18845405126312126, 0.24259669557215052),
 (0.11037074812656249, 0.19280557903930123, 0.18602638207426614),
 (0.47067740296946237, 0.26047130554497, 0.22180036378787293),
 (0.6082882275795758, 0.044682535614156346, 0.08608962040841489),
 (0.41957140738252485, 0.4393227258943449, 0.033833168889162546),
 (0.13205445536803267, 0.3082053648279024, 0.11193643182858154),
 (-0.02198775426569169, -0.3633904668703135, 0.10358276533521116),
 (0.0376628192483249, 0.04901454138003429, 0.03832515782807422)]

In [89]:
b.fitness(pressoes_reais=pressoes_r, pressoes_simuladas=resultado)

[[ 9.25383096]
 [ 9.91919699]
 [ 9.40024356]
 [ 9.51079729]
 [ 9.04705093]
 [ 9.26093962]
 [ 9.1072727 ]
 [ 9.44780375]
 [10.28179546]
 [ 9.87499748]]


array([[ 9.25383096],
       [ 9.91919699],
       [ 9.40024356],
       [ 9.51079729],
       [ 9.04705093],
       [ 9.26093962],
       [ 9.1072727 ],
       [ 9.44780375],
       [10.28179546],
       [ 9.87499748]])

In [90]:
pop = b.selecting_mating_pool(elitismo=2,num_filhos=10,mutation=0.1)

[[0.2207317  0.38482847 0.25756485 0.28818242 0.42570979]
 [0.07428928 0.405592   0.0669775  0.03780436 0.17637204]]
(7, 5)
[[0.0979056  0.4383383  0.30752582 0.296199   0.19312708]
 [0.1034277  0.33925493 0.42737845 0.36992003 0.20298743]
 [0.29554878 0.20383205 0.44759547 0.12100472 0.28178763]
 [0.35211955 0.06360977 0.32176098 0.10508009 0.22199386]
 [0.21708761 0.09137583 0.27006118 0.33473705 0.08092583]]
[[0.2207317  0.38482847 0.25756485 0.28818242 0.42570979]
 [0.07428928 0.405592   0.0669775  0.03780436 0.17637204]
 [0.0979056  0.4383383  0.30752582 0.296199   0.19312708]
 [0.1034277  0.33925493 0.42737845 0.36992003 0.20298743]
 [0.29554878 0.20383205 0.44759547 0.12100472 0.28178763]
 [0.35211955 0.06360977 0.32176098 0.10508009 0.22199386]
 [0.21708761 0.09137583 0.27006118 0.33473705 0.08092583]
 [0.32675754 0.10909638 0.35751747 0.24708747 0.14880047]
 [0.42025359 0.26648468 0.18176889 0.03281872 0.35741189]
 [0.28631172 0.19353686 0.3163006  0.08423143 0.09763133]]


In [91]:
resultado = []
for i in pop:
    resultado.append(rede(i))

In [92]:
resultado

[(0.47067740296946237, 0.26047130554497, 0.22180036378787293),
 (0.41957140738252485, 0.4393227258943449, 0.033833168889162546),
 (0.2859221261122738, 0.2267942968999721, 0.1920043911488144),
 (0.0903932979290899, 0.038199384117977506, 0.2200793633835713),
 (0.08588299276176775, 0.14026468182908436, 0.1253319339131766),
 (0.11729548282347028, -0.02734934366856517, 0.04379427696288313),
 (0.06549113125514591, -0.23596655683114937, 0.05176593613856345),
 (0.1151031780722251, -0.12175749936937788, 0.07577059374012196),
 (0.5166991825277588, 0.32891075831812905, 0.06016842427558666),
 (0.17177160382409956, 0.12820069123015862, 0.06943945384913608)]

In [93]:
pressoes_r

array([2, 3, 5])

In [94]:
b.fitness(pressoes_reais=pressoes_r, pressoes_simuladas=resultado)

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
b.fitness

In [7]:
dados_trechos = pd.read_csv('DadosTrechos_1.csv')
dados_nos = pd.read_csv('DadosNos.csv')

In [91]:
from ga_shs_MM import genetic_algorithm, HardyCross_rede

In [116]:
rede = HardyCross_rede(dados_nos=dados_nos,
                       dados_trechos=dados_trechos,
                       VazaoSaida_reservatorio=7,rugosidade=0.1)

In [117]:
rede.simular()

186.84165748086434 -1464.3695228736876 -1325.2787341669127
-361.9741266182955 -486.28798984713274 -517.4068815161852
-156.06225959303083 -306.2746103797091 -179.82669819622424
-89.00995072045725 -128.557036963447 -99.3771755567659
-39.27289732786812 -68.3095131677934 -43.694138499306064
-20.020714004624097 -31.199197928271474 -22.261774484667967
-9.314712875684563 -15.58730855739418 -10.377008007970062
-4.585869599266061 -7.357668730992145 -5.107069368140401
-2.1806683005038394 -3.5941372447596223 -2.4303985573685623
-1.0595691959952092 -1.7184010365224367 -1.1806473883320905
-0.5080653782479203 -0.832407064699737 -0.5662770510282371
-0.24562589808601842 -0.3999540148518008 -0.2737397436364972
-0.11815132115907545 -0.19313027727719145 -0.13168734632608903
-0.05701094847790955 -0.09297093465079342 -0.06353959444641077
-0.027456429076210043 -0.04484036775409095 -0.030601680422932986
-0.013238696922599047 -0.0216013286475345 -0.014754982180647858
-0.006378653406500234 -0.01041372118208983