In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

In [3]:
from ga_shs_MM import genetic_algorithm

In [5]:
a = genetic_algorithm()

Módulo aberto com sucesso!


In [6]:
init_pop = a.initial_pop(size_pop=10,size_cromossomo=4,minimum=0.1,maximum=10)
init_pop

array([[2.23919632, 8.03677528, 4.61064215, 9.05674449],
       [3.18089648, 8.46122526, 7.53742185, 6.32844107],
       [6.82203165, 3.9408722 , 7.98658304, 6.17624149],
       [1.49134   , 4.87735981, 0.92392551, 5.96631616],
       [7.84313131, 6.64557109, 3.51106874, 0.5153934 ],
       [4.95591682, 0.80247563, 1.34109771, 2.14834252],
       [4.0619631 , 2.89003292, 1.33880734, 3.46331969],
       [9.57085759, 2.82764128, 6.59319003, 5.88138687],
       [1.28710453, 6.57307959, 9.89342506, 3.31914653],
       [4.22620311, 0.13512342, 9.10183613, 0.30605104]])

In [7]:
a.funcao_obj()

[[ -38.0453726 ]
 [-109.90335855]
 [ -94.39465055]
 [   4.3069074 ]
 [  -9.56519467]
 [  34.26652014]
 [  19.27297363]
 [ -31.59586442]
 [-189.73160347]
 [-127.56742726]]


In [8]:
a.selecting_mating_pool(elitismo=3,num_filhos=10,mutation=0.1)

[[1.49134    4.87735981 0.92392551 5.96631616]
 [4.0619631  2.89003292 1.33880734 3.46331969]
 [4.95591682 0.80247563 1.34109771 2.14834252]]
(8, 4)
[[7.26338721 1.81505845 3.96714387 4.01486469]
 [8.70699445 4.73660618 5.05212939 3.19839013]
 [4.66723566 5.76146545 2.21749713 3.24085478]
 [0.49503958 3.88369636 1.13136642 4.71481792]
 [4.50893996 1.84625427 1.33995252 2.8058311 ]]
[[1.49134    4.87735981 0.92392551 5.96631616]
 [4.0619631  2.89003292 1.33880734 3.46331969]
 [4.95591682 0.80247563 1.34109771 2.14834252]
 [7.26338721 1.81505845 3.96714387 4.01486469]
 [8.70699445 4.73660618 5.05212939 3.19839013]
 [4.66723566 5.76146545 2.21749713 3.24085478]
 [0.49503958 3.88369636 1.13136642 4.71481792]
 [4.50893996 1.84625427 1.33995252 2.8058311 ]
 [2.66920612 8.62204015 1.39472357 9.61318236]
 [7.69385983 7.04107535 8.10535705 7.27476262]]
