In [5]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [6]:
import numpy as np
import pandas as pd

In [7]:
from ga_shs_MM import genetic_algorithm

In [8]:
b = genetic_algorithm()

Módulo aberto com sucesso!


In [9]:
init_pop = b.initial_pop(size_pop=10,size_cromossomo=5,minimum=0.01,maximum=0.5)
init_pop

array([[0.06745446, 0.02805148, 0.47083629, 0.16767499, 0.27236904],
       [0.27434987, 0.27372355, 0.23367147, 0.43955097, 0.44317704],
       [0.37956881, 0.08017302, 0.42830439, 0.49663934, 0.15506017],
       [0.47603781, 0.48995229, 0.22336703, 0.14710537, 0.08587872],
       [0.17784423, 0.30371908, 0.45388876, 0.28259101, 0.09378969],
       [0.12398279, 0.30087301, 0.23436542, 0.37797305, 0.4245802 ],
       [0.33847981, 0.2626237 , 0.46886114, 0.03153609, 0.02141694],
       [0.10291354, 0.43496056, 0.26487959, 0.1929739 , 0.11054547],
       [0.06344473, 0.41355419, 0.35249434, 0.23443967, 0.24245607],
       [0.346522  , 0.39768194, 0.28480346, 0.05699566, 0.32904902]])

In [10]:
pressoes_r = np.array([2, 3, 5])
def rede(rugosidade):
    pressaoes_0 = rugosidade[0] +rugosidade[1]-rugosidade[2]+rugosidade[4]*rugosidade[3] 
    pressaoes_1 = rugosidade[1]-rugosidade[3]-rugosidade[2]+rugosidade[2]+rugosidade[1]*rugosidade[4]
    pressaoes_2 = rugosidade[4]*rugosidade[3]+rugosidade[2]+rugosidade[1]*rugosidade[2]-rugosidade[2]
    return (pressaoes_0,pressaoes_1,pressaoes_2)

In [11]:
resultado = []
for i in init_pop:
    resultado.append(rede(i))

In [12]:
resultado

[(-0.3296608670681549, -0.13198315638408428, 0.05887713172832476),
 (0.509200843251676, -0.04451942640474163, 0.2587602782149151),
 (0.10844642464822278, -0.4040346706486964, 0.11134743726037494),
 (0.755256291246385, 0.38492339972371237, 0.12207240717836884),
 (0.05417867830459612, 0.04961379126869671, 0.16435879901920725),
 (0.3509702502207871, 0.05064468692916063, 0.2309941007061225),
 (0.13291777702715538, 0.23671220920369396, 0.12380945636350144),
 (0.29432689804588963, 0.29006958268551214, 0.13654456579483465),
 (0.18134590305155066, 0.27938324428670513, 0.2026168319174208),
 (0.47815484236200295, 0.47154314090960414, 0.1320155586101423)]

In [13]:
b.fitness(pressoes_reais=pressoes_r, pressoes_simuladas=resultado)

[[10.40276689]
 [ 9.2765583 ]
 [10.18424081]
 [ 8.7377479 ]
 [ 9.73184873]
 [ 9.36739096]
 [ 9.50656056]
 [ 9.27905895]
 [ 9.33665402]
 [ 8.91828646]]


array([[10.40276689],
       [ 9.2765583 ],
       [10.18424081],
       [ 8.7377479 ],
       [ 9.73184873],
       [ 9.36739096],
       [ 9.50656056],
       [ 9.27905895],
       [ 9.33665402],
       [ 8.91828646]])

In [14]:
pop = b.selecting_mating_pool(elitismo=2,num_filhos=10,mutation=0.1)

[[0.47603781 0.48995229 0.22336703 0.14710537 0.08587872]
 [0.346522   0.39768194 0.28480346 0.05699566 0.32904902]]
(7, 5)
[[0.09571862 0.16446225 0.35260085 0.27282402 0.34847462]
 [0.2312313  0.28174836 0.35161328 0.20475457 0.22299857]
 [0.25816202 0.28317139 0.46137495 0.15706355 0.44205216]
 [0.27870652 0.19194605 0.44109657 0.38961517 0.12442493]
 [0.22351164 0.05411225 0.44957034 0.33215716 0.2137146 ]]
[[0.47603781 0.48995229 0.22336703 0.14710537 0.08587872]
 [0.346522   0.39768194 0.28480346 0.05699566 0.32904902]
 [0.09571862 0.16446225 0.35260085 0.27282402 0.34847462]
 [0.2312313  0.28174836 0.35161328 0.20475457 0.22299857]
 [0.25816202 0.28317139 0.46137495 0.15706355 0.44205216]
 [0.27870652 0.19194605 0.44109657 0.38961517 0.12442493]
 [0.22351164 0.05411225 0.44957034 0.33215716 0.2137146 ]
 [0.46510711 0.3690913  0.27894623 0.28938277 0.3426415 ]
 [0.26137542 0.20371666 0.40435905 0.47179897 0.07769085]
 [0.39789531 0.27495362 0.46866251 0.16968563 0.22634086]]


In [15]:
resultado = []
for i in pop:
    resultado.append(rede(i))

In [16]:
resultado

[(0.755256291246385, 0.38492339972371237, 0.12207240717836884),
 (0.47815484236200295, 0.47154314090960414, 0.1320155586101423),
 (0.0026522638204812266, -0.051050855178944664, 0.15306177450296216),
 (0.2070263507240578, 0.13982326925319732, 0.14472644035419452),
 (0.14938874512012384, 0.25128436975105267, 0.20007846909438975),
 (0.07803384031633841, -0.17378624581682733, 0.13314458581086197),
 (-0.1009596127329712, -0.2664803338146546, 0.09531409999313578),
 (0.6544067299022288, 0.20617452798730287, 0.20211117035395726),
 (0.09738749696313066, -0.2522553896011713, 0.11902913940989512),
 (0.24259321737560124, 0.16750122812501425, 0.16726724278867589)]

In [17]:
pressoes_r

array([2, 3, 5])

In [18]:
b.fitness(pressoes_reais=pressoes_r, pressoes_simuladas=resultado)

TypeError: 'numpy.ndarray' object is not callable

In [ ]:
b.fitness

In [19]:
dados_trechos = pd.read_csv('DadosTrechos_1.csv')
dados_nos = pd.read_csv('DadosNos.csv')

In [76]:
from ga_shs_MM import HardyCross_rede

In [89]:
rede = HardyCross_rede(dados_nos=dados_nos,
                       dados_trechos=dados_trechos,
                       VazaoSaida_reservatorio=7,rugosidade=0.5)

In [90]:
rede.simular()

     Trecho  Q_iterativo_1  Q_iterativo_2  Q_iterativo_3
0     R - 1            NaN            NaN            NaN
1     1 - 2      -2.576985       2.576985            NaN
2     2 - 3      -2.331985       2.331985            NaN
3    3 - 13            NaN            NaN       1.651101
4    3 - 12       0.104830            NaN            NaN
5   12 - 11       0.587830            NaN            NaN
6   11 - 10       0.979830            NaN            NaN
7    10 - 9       1.364830            NaN            NaN
8     9 - 1       1.651830            NaN            NaN
9   13 - 14            NaN            NaN       1.077101
10  14 - 15            NaN            NaN       0.601101
11  15 - 16            NaN            NaN      -0.217899
12  16 - 17            NaN            NaN      -0.714899
13   17 - 5            NaN            NaN      -0.861899
14    5 - 4            NaN       0.197713      -0.197713
15    4 - 3            NaN       0.400713      -0.400713
16    5 - 6            NaN     

In [91]:
rede.resultado_pressao()

(26.734337748449235, 34.46351328417657, 32.41212094424557)