In [2]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
import numpy as np

In [5]:
from ga_hcmatrix import genetic_algorithm, HC_numpy_matrix

In [6]:
dados_trechos_np = np.loadtxt('DadosTrechos_1.csv',delimiter=',',usecols=[1,2],skiprows=1)
dados_nos_np = np.loadtxt('DadosNos.csv', delimiter=',',usecols=1,skiprows=1)
dados_calibracao_np = np.loadtxt('DadosCalibracao.csv', delimiter=',',skiprows=1)

In [24]:
ga = genetic_algorithm()

Módulo aberto com sucesso!
a1


In [27]:
%prun ga.jarvis(dados_nos=dados_nos_np, dados_trechos=dados_trechos_np, dados_calibracao=dados_calibracao_np)

8.460054976450031
[0.25513555 0.97120904 0.10228313 0.07251567 0.9118362  0.89293753
 0.2491955  0.61882053 0.55065244 0.67758102 0.07900337 0.71782622
 0.40068597 0.68285502 0.86571896 0.1464284  0.95539456 0.30571941
 0.29694237 0.2210901 ]

8.026104297475868
[0.27224305 0.18419571 0.07874626 0.79711994 0.16134541 0.68927325
 0.71824831 0.21269929 0.37048232 0.31205111 0.49742021 0.96692211
 0.27282753 0.08452658 0.92631351 0.35069719 0.41877891 0.12157208
 0.03267523 0.6346051 ]

8.026104297475868
[0.27224305 0.18419571 0.07874626 0.79711994 0.16134541 0.68927325
 0.71824831 0.21269929 0.37048232 0.31205111 0.49742021 0.96692211
 0.27282753 0.08452658 0.92631351 0.35069719 0.41877891 0.12157208
 0.03267523 0.6346051 ]

8.026104297475868
[0.27224305 0.18419571 0.07874626 0.79711994 0.16134541 0.68927325
 0.71824831 0.21269929 0.37048232 0.31205111 0.49742021 0.96692211
 0.27282753 0.08452658 0.92631351 0.35069719 0.41877891 0.12157208
 0.03267523 0.6346051 ]

8.026104297475868
[0.272

         9806803 function calls (9802803 primitive calls) in 47.350 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   816138   17.495    0.000   17.895    0.000 ga_hcmatrix.py:175(perdaCarga_unitaria_Universal)
    72000   13.804    0.000   43.608    0.001 ga_hcmatrix.py:214(simular)
   600138    6.053    0.000   11.785    0.000 ga_hcmatrix.py:198(vazaoCorretiva_Universal)
  1200676    3.583    0.000    3.583    0.000 {method 'reduce' of 'numpy.ufunc' objects}
  1117338    2.375    0.000    2.375    0.000 {built-in method numpy.array}
  3153422    0.960    0.000    0.960    0.000 {built-in method builtins.abs}
  1200276    0.713    0.000    4.580    0.000 {method 'sum' of 'numpy.ndarray' objects}
    72000    0.694    0.000    1.613    0.000 ga_hcmatrix.py:151(__init__)
      200    0.483    0.002   47.097    0.235 ga_hcmatrix.py:36(funcao_rede)
    72000    0.444    0.000    0.985    0.000 ga_hcmatrix.py:249(resultado_pre

In [19]:
vazaos = [21]

In [20]:
e = np.array([0.02346506, 0.33968424, 0.62800914, 0.03360937, 0.37554997, 0.57865363,0.61527742, 0.93079331, 0.07842162, 0.20689928, 0.49569957, 0.83336383,0.51315951, 0.99549124, 0.151544,0.55775464, 0.75020367, 0.25868925,0.03703703, 0.0465057 ])

In [22]:
for i in vazaos:
    rede = HC_numpy_matrix(dados_trechos=dados_trechos_np,dados_nos=dados_nos_np,VazaoSaida_reservatorio=i,rugosidade=e)
    rede.simular()
    print(rede.resultado_pressao())

[[10 10 10]]
[[-1.16937683  0.47337939 -1.6757225 ]]
[[-0.11256961 -0.53372842 -0.46834035]]
[[-0.13613476 -0.22950212 -0.2179919 ]]
[[-0.06488439 -0.12297264 -0.08945966]]
[[-0.03389127 -0.05494818 -0.04649353]]
[[-0.01531538 -0.02746852 -0.02069822]]
[[-0.00755051 -0.012446   -0.0101272 ]]
[[ 0.          0.          0.        ]
 [-7.49046178  7.49046178  0.        ]
 [-6.75546178  6.75546178  0.        ]
 [ 0.          0.          5.00554909]
 [ 0.27683359  0.          0.        ]
 [ 1.72583359  0.          0.        ]
 [ 2.90183359  0.          0.        ]
 [ 4.05683359  0.          0.        ]
 [ 4.91783359  0.          0.        ]
 [ 0.          0.          3.28354909]
 [ 0.          0.          1.85554909]
 [ 0.          0.         -0.60145091]
 [ 0.          0.         -2.09245091]
 [ 0.          0.         -2.53345091]
 [ 0.          0.26274627 -0.26274627]
 [ 0.          0.87174627 -0.87174627]
 [ 0.         -4.32870464  0.        ]
 [ 0.         -5.29470464  0.        ]
 [ 0.